### ISSUE TITLE
Instead of writing null for the init data by write nothing

### ISSUE THREAD

**Issue by KaroseLiu** [jsoendermann/MongoStyleGuide#2]
Right now, we have a document data structure like this:
```
{
  height: 168,
  weight: 65,
  name: 'Karose',
  profile: {
    wechatInfo: {
      nickname: '不在迷津',
      avatar: '/img/....',
      details: {
        vip: ['aa'],
      },
    },
  },
}
```
Scene 1：
If in the FD, we only save **name** property, we just need save like below:
```
{
  name: 'Karose',
}
```
But right now, the mongo style is like:
```
{
  height: null,
  weight: null,
  name: 'Karose',
  profile: {
    wechatInfo: {
      nickname: null,
      avatar: null,
      details: {
        vip: null,
      },
    },
  },
}
```
So it's not easy to loop all the properties to set **null**, so we could have a compromise solution：

When we never touch or change the data, we do nothing for them, If we change the data from existed value to empty, so we need set the property to **null**

**Comment by jsoendermann** [comment]
I think this is a good suggestion for primitive types like numbers, strings and bools.

For objects or arrays, it introduces the danger of `Cannot read property '...' of undefined` errors . In your example, if you have an object `obj = { name: 'Karose' }` and somebody accesses `obj.profile.wechatInfo`, your app crashes. This basically means we have to use lodash.get to access any property more than one level deep.

Most of the stuff we save comes from redux, right? The difference for redux is whether you write `INITIAL_STATE = {}` or the full object tree like in your example. I like explicit initial states, also for documentation purposes. What do you think?

In any case, I think this is definitely one of the questions where we should settle on one or the other and be consistent in how we save things.
